def steadystate_to_grins(path_to_data : str, zero_cutoff : int):
    """
    Takes a .parquet file containing the steady states generated by GRiNS-Racipe and turns it into an AnnData object.
    Do note that the steady state entries in grins_data.X are not discrete. 

    Parameters:
    -----------
    path_to_data : str
        A path to the file name of the data generated by GRiNS, without the name extension (.parquet, .csv, .h5ad, ...).
    zero_cutoff : float
        A threshold where steady state concentrations below this value will be set to 0.

    Returns:
    --------
    grins_data : anndata
        An AnnData object containing the GRiNS steady state solutions.
    """

    print(f"Read {path_to_data}.parquet...")
    sol_df = pd.read_parquet(f"{path_to_data}.parquet")
    
    # Create the AnnData object:
    print("Create AnnData object...")
    gk_cols = [col for col in sol_df.columns if "gk_" in col]
    gene_cols = [col.replace("gk_", "") for col in sol_df.columns if "gk_" in col]
    sol_matrix = sol_df.loc[:,gene_cols].values
    if zero_cutoff > 0.0:
        for i in range(sol_matrix.shape[0]):
            if i % 100000 == 0:
                print(i)
            for j in range(sol_matrix.shape[1]):
                if sol_matrix[i,j] < zero_cutoff:
                    sol_matrix[i,j] = 0
    
    sol_sparse = sparse.csc_matrix(sol_matrix)
    grins_data = ad.AnnData(sol_sparse)
    grins_data.obs_names = [str(sol_df.loc[:,"param_index"][i])+"_"+str(sol_df.loc[:,"ic_index"][i]) for i in range(sol_df.shape[0])] # InitCondNum and ParamNum also exist!!!
    grins_data.var_names = gene_cols
    return grins_data


def discrete_to_grins(path_to_data : str, is_racipe : bool):
    """
    Takes the state counts saved in a .csv file and turns them into an Anndata object.
    Do note that the on/off states in grins_data.X should not be regarded as counts whatsoever.

    Parameters:
    -----------
    path_to_data : str
        A path to the file name of the data generated by GRiNS, without the name extension (.parquet, .csv, .h5ad, ...).
    is_racipe : bool
        A boolean to indicate whether or not the data is generated through Racipe (True) or Ising (False).

    Returns:
    --------
    grins_data : anndata
        An AnnData object containing the discrete states of GRiNS.
    """
    pass


def normalize_grins(grins_data):
    """
    Takes the AnnData object just created and normalized it, following the normalization pipeline from the software project.
    """

    # Log-normalize the layers:
    print("Normalize Data...")
    grins_data.layers["normalized"] = grins_data.X.copy()
    sc.pp.normalize_total(grins_data, target_sum=None,layer="normalized")
    grins_data.layers["log1p"] = grins_data.layers["normalized"].copy()
    sc.pp.log1p(grins_data, layer="log1p")
    
    # Calculate QC metrics:
    print("Calculate QC metrics...")
    sc.pp.calculate_qc_metrics(grins_data,percent_top=[20],inplace=True)

    return grins_data


def grins_to_adata(path_to_data : str, is_racipe : bool, is_discrete : bool = True, zero_cutoff : float = 0.0):
    """
    Turns either the steady states generated by Racipe or the discrete on/off states generated by Racipe or Ising and turns them into an Anndata object.

    Parameters:
    -----------
    path_to_data : str
        A path to the file name of the data generated by GRiNS, without the name extension (.parquet, .csv, .h5ad, ...).
    is_racipe : bool
        A boolean indicating whether or not the data is generated through Racipe (True) or Ising (False).
    is_discrete : bool
        A boolean indicating whether the steady states.
    zero_cutoff : float
        A threshold where steady state concentrations below this value will be set to 0.

    Returns:
    --------
    grins_data : anndata
        An AnnData object containing the discrete states of GRiNS.

    Examples:
    ---------
    racipe_data = grins_to_adata(path_to_data, is_racipe = True, is_discrete = False, zero_cutoff = 0.1)
    ising_data = grins_to_adata(path_to_data, is_racipe = False)
    """
    # Get file path to data:
    if is_racipe:
        if is_discrete: # Discrete RACIPE state counts
            path_to_data = f"Data/SimulResults_Racipe/{topo}/00{replicate}/{topo}_steadystate_counts_00{replicate}"
        else: # Continuous RACIPE concentrations
            path_to_data = f"Data/SimulResults_Racipe/{topo}/00{replicate}/{topo}_steadystate_solutions_00{replicate}-{str(zero_cutoff).replace(".","_")}"
    else:
        if is_sync: # Sync Ising state counts
            path_to_data = f"Data/SimulResults_Ising/{topo}/{replicate}/{topo}_sync_ising_results"
        else: # Async Ising state counts
            path_to_data = f"Data/SimulResults_Ising/{topo}/{replicate}/{topo}_async_ising_results"


    # Get AnnData object:
    if not os.path.isfile(f"{path_to_data}.h5ad"):
        if is_discrete:
            grins_data = discrete_to_grins(path_to_data, is_racipe) 
        else:
            if not is_racipe:
                raise Exception("Ising does not generate any steady states. Therefore, is_discrete = False and is_racipe = False are not compatible.")
            grins_data = steadystate_to_grins(path_to_data.split("-")[0], zero_cutoff) # Remove the zero_cutoff index from the data path
        # Normalize:
        grins_data = normalize_grins(grins_data)    

        # Save the object:
        print(f"Save the AnnData object to {path_to_data}.h5ad...")
        ad.settings.allow_write_nullable_strings = True # <- remove later
        grins_data.write_h5ad(
            f"{path_to_data}.h5ad", # maybe change path later
            compression=hdf5plugin.FILTERS["zstd"]
        )
    else:
        print("Reading h5ad file...")
        grins_data = sc.read_h5ad(f"{path_to_data}.h5ad")    

    return grins_data


def save_full_grins():
    # Takes the adata object from control and perturb cells as input, concatenates them, and saves them as full h5ad file
    pass


def missingness_filter():
    # If control data is available: maybe use something like scImpute (https://pmc.ncbi.nlm.nih.gov/articles/PMC12908672/) to find probability of a zero being a dropout
    # Then calculate for each gene the percentage of dropouts and use that to create dropouts in synth data

    # Otherwise, maybe do the same but average over literature data? if that exists?

    # New general idea:
    """
    if control_data supplied:
        fit gamma-norm prob on the expression histogram across all control cells j for each gene i
        lambda_biol,i is the biological dropout rate; compare it to dropout rate lambda_grins,i in grins (which should all be biological)
        maybe scale lambda_tech,i somehow so that lambda_biol,i=lambda_grins,i?
        lambda_total,i=lambda_tech,i+lambda_biol,i=1-nnv/n
        however, scaling it like this (multiplying by lamba_biol/lambda_grins=k) could mean that k(1-nnv/n)>1, which doesnt make sense
        finally: 
    """

    # Other approach:
    """
    say that lambda_biol,i=lambda_grins,i and simply set lambda_tech,i=1-nnv/n-lambda_grins,i
    then, plot the mean of the non-dropout expression levels for each gene against its lambda_tech,i technical dropout rate and fit a curve
    use this curve to impute how many non-zero entries in grins should be set to 0 (tech dups)

    but what if (theoretically) lambda_grins,i > 1-nnv/n -> lambda_tech,i<0
        especially the case if some gene is always zero in grins because of GRN design
        maybe skip those (already enough missingness)
    """

    # Approach without control data, purely from grins:
    """
    Idea: 
    """
    pass

def get_dist_matrix():
    pass

def calc_clusters():
    # Silhouette Score
    # How to deal with multiple control datasets? Maybe calc clusters for all of them and find the best mean?
    # Probably also need to subset the genes in GRN for each dataset
    pass

def reduce_param_ranges():
    # Get param ranges of best cluster as .csv
    # 
    pass

def set_param_ranges():
    pass


def main():
    pass

if __name__ == "__main__":
    main()