import numpy as np
import pandas as pd
import random

import scipy
from scipy import sparse
from scipy.stats import expon

import anndata as ad
import hdf5plugin
import scanpy as sc

import os
import argparse
from tqdm import tqdm
from glob import glob

try:
    import pgrins_prepare_input
except:
    from Prep_Data import pgrins_prepare_input

def grins_racipe_to_adata(path_to_data : str, pert_list : list = None) -> ad.AnnData:
    """
    Takes a .parquet file containing the steady states generated by GRiNS-Racipe and turns it into an AnnData object.
    Do note that the steady state entries in grins_data.X are not discrete. 

    Parameters:
    -----------
    path_to_data : str
        A path to the file name of the data generated by GRiNS, without the name extension (.parquet, .csv, .h5ad, ...).
    pert_list : list, optional
        A list of dictionaries for each perturbation set, if applicable.
    max_missingness : float, optional
        The maximal percentage of cells for each gene that should be able to be missing.
    expon_scale : float, optional
        The scale of the exponential distribution used for missingness sampling.
    full_dropouts : float, optional
        How many genes should have 100% missingness.

    Returns:
    --------
    grins_data : ad.AnnData
        An AnnData object containing the GRiNS steady state solutions.
    """

    print(f"Read {path_to_data}...")
    if pert_list is None:
        nonsink_df = pd.read_parquet(f"{path_to_data}_ctrl.parquet")
        sink_df = pd.read_parquet(f"{path_to_data}_sinks_ctrl.parquet")
    else:
        nonsink_df = pd.read_parquet(f"{path_to_data}_pert.parquet")
        sink_df = pd.read_parquet(f"{path_to_data}_sinks_pert.parquet")

    info_df = nonsink_df.loc[:,["PertNum","InitCondNum","ParamNum"]] # Contains combination of ICs and params and perts
    nonsink_df = nonsink_df.loc[:,list([col.replace("gk_", "") for col in nonsink_df.columns if "gk_" in col])] # Contains expression values
    
    sol_df = pd.concat([nonsink_df,sink_df],axis=1)
    sol_df = sol_df.reindex(sorted(sol_df.columns),axis=1)
    
    
    # QC:
    zero_genes = pd.Series([np.sum(sol_df[col]==0) for col in list(sol_df.columns)])
    minus_genes = pd.Series([np.sum(sol_df[col]<0) for col in list(sol_df.columns)])
    na_genes = pd.Series([np.sum(sol_df[col].isna()) for col in list(sol_df.columns)])
    print(f"There are {np.sum(zero_genes)} zero entries ({np.round(100*np.sum(zero_genes)/(sol_df.shape[0]*sol_df.shape[1]),3)}% of all entries), {np.sum(minus_genes>sol_df.shape[0]*0.01)} genes with more than 1% of entries being negative ({np.round(100*np.sum(minus_genes>sol_df.shape[0]*0.01)/sol_df.shape[1],3)}% of all genes), and {np.sum(na_genes>sol_df.shape[0]*0.01)} genes with more than 1% of entries being NaN ({np.round(100*np.sum(na_genes>sol_df.shape[0]*0.01)/sol_df.shape[1],3)}% of all genes).")

    sol_df = sol_df.fillna(0)
    sol_df[sol_df[:]<0]=0 # There are negative entries for some reason    
    
    # Create the AnnData object:
    print("Create AnnData object...")
    grins_data = ad.AnnData(sparse.csc_matrix(sol_df.values))
    grins_data.obs = info_df
    
    # Add perturbation column
    if pert_list is None:
        grins_data.obs["PertNum"] = -1
        grins_data.obs["perturbation"] = "ctrl"
    else:
        grins_data.obs["perturbation"] = np.array(["_".join(sorted(list(pert_list[int(i)].keys()))) for i in grins_data.obs["PertNum"].values])
    grins_data.obs_names = [f"{int(info_df.loc[:,"PertNum"][i])}_{int(info_df.loc[:,"InitCondNum"][i])}_{int(info_df.loc[:,"ParamNum"][i])}" for i in range(info_df.shape[0])]
    grins_data.var_names = list(sol_df.columns)

    return grins_data



def normalize_grins_adata(grins_data : ad.AnnData) -> ad.AnnData:
    """
    Takes the AnnData object just created and normalized it, following the normalization pipeline from the software project.

    Parameters:
    -----------
    grins_data : ad.AnnData
        The unnormalized AnnData object containing the simulation results.
    """
    # Calculate QC metrics:
    print("Calculate QC metrics...")
    sc.pp.calculate_qc_metrics(grins_data,percent_top=[20],inplace=True,log1p=True)

    # Log-normalize the layers:
    print("Normalize Data...")  
    grins_data.layers["log1p"] = grins_data.X.copy().tocsc()
    sc.pp.normalize_total(grins_data, target_sum=None,layer="log1p")

    sc.pp.log1p(grins_data, layer="log1p")
    return grins_data



def grins_ising_to_adata(path_to_data : str, grn_file : str) -> ad.AnnData:
    """
    Takes the state counts saved in a .csv file and turns them into an Anndata object.
    Do note that the on/off states in grins_data.X should not be regarded as counts.

    Parameters:
    -----------
    path_to_data : str
        A path to the file name of the data generated by GRiNS, without the name extension.
    grn_file : str
        The name of the project.

    Returns:
    --------
    grins_data : ad.AnnData
        An AnnData object containing the discrete states of GRiNS.
    """
 
    print(f"Read {path_to_data}.csv...")
    sol_df = pd.read_csv(f"{path_to_data}.csv")
    sol_matrix = np.asarray([list(string) for string in sol_df["State"].values],dtype=int) # if '100101011...', then list(string[1:-1])
    grn = pd.read_csv(f"Data/{grn_file}/{grn_file}.topo",sep=" ")
    grn_genes = sorted(list(set(grn["Source"])|set(grn["Target"])))

    sol_sparse = sparse.csc_matrix(sol_matrix)
    grins_data = ad.AnnData(sol_sparse)
    grins_data.obs_names = sol_df["Initnum"]
    grins_data.var_names = grn_genes
    grins_data.obs["Replicate"] = sol_df["Replicate"].values
    grins_data.obs["Mode"] = sol_df["Mode"].values

    return grins_data



def get_subset_adata_all(grins_data : ad.AnnData, grn_file : str, ctrl_only : bool = False, max_missingness : int = 90) -> tuple[ad.AnnData, dict[str,ad.AnnData]]:
    """
    Returns all experimental adata files, and asserts that the contained in the GRiNS data are the same as in the union of genes from the experimental datasets.

    
    """

    adata_dict = {pseq_path.split("/")[-1] : sc.read_h5ad(f"{pseq_path}/perturb_norm.h5ad") for pseq_path in glob(f"Data/Experimental/*")}
    
    for name, adata in adata_dict.items():
        adata_dict[name] = adata[:,adata.var["pct_dropout_by_counts"]<max_missingness]

    grins_gnames = set(grins_data.var_names)
    adata_gnames = set().union(*[set(adata.var_names) for adata in adata_dict.values()])
    grins_gnames = grins_gnames & adata_gnames # Only genes in adata remain in grins_data
    grins_data = grins_data[:,sorted(list(grins_gnames))]

    for name, adata in adata_dict.items():
        if ctrl_only:
            adata_dict[name] = adata[adata.obs["perturbation"]=="ctrl"]
        else:
            # Remove all perturbations not in the .pert file
            adata_dict[name] = adata[adata.obs["perturbation"].isin(list(grins_data.obs["perturbation"]).unique()+["ctrl"])]
        adata_gnames = set(adata.var_names)
        adata_dict[name] = adata[:,sorted(list(grins_gnames & adata_gnames))] # Only genes in grins_data remain in each adata
        print(f"Save subset of {name}...")
        ad.settings.allow_write_nullable_strings = True
        adata_dict[name].write_h5ad(
            f"Data/Experimental/{name}/perturb_norm_subset_{grn_file}.h5ad",
            compression=hdf5plugin.FILTERS["zstd"]
        )      

    return grins_data


def apply_missingness(grins_data : ad.AnnData, inplace : bool = True) -> ad.AnnData:
    """
    Takes the missing value information from missingness_filter and applies it to a layer.

    Parameters:
    -----------
    grins_data : ad.AnnData
        The grins data object.
    layer : str, optional
        The layer to apply the missingness to. If None, use grins_data.X
    inplace : bool, optional
        Whether or not this should be done inplace (if True, the QC metrics calculated on the raw data will be overwritten!)

    Returns:
    --------
    grins_data : ad.AnnData
        The modified grins data input.
    """
    if inplace:
        data = grins_data
    else:
        data = grins_data.copy()

    print("Applying missingness filter...")
    data.obs.rename(columns=dict(zip([c for c in list(data.obs.columns) if "counts" in c],[f"nm_{c}" for c in list(data.obs.columns) if "counts" in c])),inplace=True) # Rename old QC columns to nonmissing (nm_)
    data.var.rename(columns=dict(zip([c for c in list(data.obs.columns) if "counts" in c],[f"nm_{c}" for c in list(data.obs.columns) if "counts" in c])),inplace=True)
    data.layers["log1p"]=sparse.csc_matrix.multiply(data.layers["log1p"].tocsc(),data.layers["missing_matrix"].tocsc()).tocsc()

    # Calculate QC metrics:
    sc.pp.calculate_qc_metrics(data,percent_top=[20],inplace=True,log1p=True,layer="log1p")
    return data


def get_full_grins():
    # Takes the parquet files from control and perturb cells as input, concatenates them, applies missingness, and saves them as full h5ad file
    # In case colnames dont align between them: set everything missing to 0
    # 
    pass



def missingness_filter(grins_matrix : np.matrix, loc : float = 10, scale : float = 42.2, full_dropouts : float = 0) -> list:
    """
    Inserts missing entries into the raw grins matrix (m cells, n genes) according to the following procedure:
        1. n missing counts l_hat are sampled from an exponential distribution fit to the Replogle dataset (meaning without full dropouts, aka. pct_dropouts<=90)
            - Since the distribution is fit from [0,inf), but the data is in [10,100], so it is first shifted to [0,90].
            - Then, the mean of the counts is calculated as mu, and loc=0 and lambda=scale=1/mu are used (alternatively, it is also possible to fit scipy.stats.expon to the histogram).
            - During sampling, +10 is added to all values, and those that exceed 100 are set to 100; this is also sensible since there is a significant amount of genes with exactly 0 dropouts, which an exponential distribution alone would not capture.
        2. Assuming that a gene with a lower average expression should have more missing entries, both the average expressions across genes and the l_hat are ranked.
        3. Each gene j is assigned the l_hat,j of the same rank, meaning that it should have that many missing entries.
        4. Each entry ij should have a higher missingness probability the lower its expression is; therefore, assign the probability 1/(x_ij+1), and normalize these so that all probabilities add up to 1.
        5. Perform Weighted Random Sampling (WRS) without replacement using an algorithm described by Efraimidis and Spirakis (2005) to set l_hat,j many entries to 0.
    This way, only the entries with the highest expression for low-expression genes will be kept, while high-expression genes will only have few genes removed.

    Parameters:
    -----------
    grins_matrix : np.matrix
        The raw counts.
    loc : float, optional
        How far to the right the distribution should be shifted. 100-max_missingness.
    scale : float, optional
        The scale of the exponential distribution used for missingness sampling.
    full_dropouts : float, optional
        How many genes should have 100% missingness.

    Returns:
    missing_indices : sparse.csc_matrix
        A sparse matrix where all dropout entries are 0 and all entries to be kept are 1.

    Code for params generation (adjust the bins size until distribution fits histogram well):
        plt.hist(100-replogle_data.var["pct_dropout_by_counts"],bins=100,density=True)
        plt.xlim(0,100)
        x = np.linspace(0,100,1000)
        plt.plot(x,expon.pdf(x,loc=10,scale=np.mean(100-replogle_data.var["pct_dropout_by_counts"])))
        plt.plot()
        plt.show()
    """
    
    expon_params = (loc,scale) # (10,42.2) for Replogle
    missing_matrix = np.ones(grins_matrix.shape)
    gene_mean_order = np.asarray(np.argsort(np.mean(grins_matrix,axis=0))).squeeze()[::-1] # Sorted from high to low expression
    rvs = np.array([x if x < 100 else np.float64(100) for x in expon.rvs(*expon_params,size=grins_matrix.shape[1])]) # pct_dropout_by_counts is on interval [0,100], so all values above 100 (0% dropout) make no sense
    missing_rates = np.sort((grins_matrix.shape[0]*(1-rvs/100)).astype(int)) # The number of missing cells per gene with same rank, 1-x/100 is necessary because rvs contains the percentage of cells not missing
                                                                             # Sorted from low to high number of dropouts
    print(f"{100*np.sum(missing_rates)/(grins_matrix.shape[0]*grins_matrix.shape[1])}% of entries will become missing") # should be around 56%
    
    for j in tqdm(range(len(gene_mean_order))): # Start with gene with highest expression level, assign to it the lowest dropout rate
        # Calculate the number of already zero entries (biological zeroes); if there are more than missing_rates[j], no technical zeroes need to be added
        nonzero_rows = np.where(np.asarray(grins_matrix[:,gene_mean_order[j]]).squeeze()!=0)[0]
        
        if grins_matrix.shape[0]-len(nonzero_rows)>=missing_rates[j]:
            continue
        gene_missing_prob = (1/((grins_matrix[nonzero_rows,gene_mean_order[j]]+1)*np.sum(1/(grins_matrix[nonzero_rows,gene_mean_order[j]]+1)))) # Probability for each cell that a gene is missing; add up to 1
        # Weighted random sampling across the cells:
        keys = np.exp(np.random.rand(len(nonzero_rows)),1/gene_missing_prob)
        # Make probability of nonzero positions becoming zero zero:
        prob_pos = np.zeros(grins_matrix.shape[0])
        # Assign missingness probabilities to remaining nonzero positions:
        prob_pos[nonzero_rows] = keys
        wrs_positions = np.argsort(prob_pos)[::-1][:missing_rates[j]-(grins_matrix.shape[0]-len(nonzero_rows))] # Get a number of entries equal to the lambda with the same rank as the gene mean expression
        if len(wrs_positions)>0:
            missing_matrix[wrs_positions,gene_mean_order[j]]=0

    # Add full dropouts, if desired
    num_dropouts = int(missing_matrix.shape[1]*full_dropouts)
    if num_dropouts > 0:
        missing_matrix[random.sample(list(range(missing_matrix.shape[1])),num_dropouts),:] = 0
    
    #missing_X = sparse.csc_matrix(np.multiply(grins_matrix,missing_matrix))
    
    return sparse.csc_matrix(missing_matrix)#missing_X
    


def main(grn_file : str, experimental : bool, is_racipe : bool = True, pert_file : str = None, num_replicates : int = 1, mode : str = "async", max_missingness : float = 90, expon_scale : float = 42.2, full_dropouts : float = 0) -> ad.AnnData:
    """
    Turns either the steady states generated by Racipe or the discrete on/off states generated by Racipe or Ising and turns them into an Anndata object.

    Parameters:
    -----------
    grn_file : str
        The name of the project
    is_racipe : bool
        A boolean indicating whether or not the data is generated through Racipe (True) or Ising (False).
    pert_file : str, optional
        Name of the .pert file, if applicable.
    max_missingness : float, optional
        The maximal percentage of cells for each gene that should be able to be missing.
    expon_scale : float, optional
        The scale of the exponential distribution used for missingness sampling.
    full_dropouts : float, optional
        How many genes should have 100% missingness.
    num_replicates : int, optional
        The number of replicates for the simulation.
    mode : bool, optional
        Indicating whether or not the Ising results are generated using sync or async updates.

    Returns:
    --------
    grins_data : ad.AnnData
        An AnnData object containing the discrete states of GRiNS.

    Examples:
    ---------
    racipe_data = grins_to_adata(path_to_data, is_racipe = True)
    ising_data = grins_to_adata(path_to_data, is_racipe = False, mode="sync")
    """
    assert max_missingness >= 0 and max_missingness <= 100
    assert expon_scale >= 0
    assert full_dropouts >= 0 and full_dropouts <= 100

    if pert_file is not None:
        pert_list = pgrins_prepare_input.extract_pert_info(grn_file,pert_file)
        suffix = "pert"
    else:
        pert_list = None
        suffix = "ctrl"

    for replicate in range(1,num_replicates+1):
        # Get file path to data:
        if is_racipe:
            path_to_data = f"Data/SimulResults_Racipe/{grn_file}/{replicate:03}/{grn_file}_steadystate_solutions_{replicate:03}"
        else:
            path_to_data = f"Data/SimulResults_Ising/{grn_file}/{replicate}/{grn_file}_{mode}_SteadyStates"

        return_path = f"Data/Projects/{grn_file}/perturb_norm_{suffix}.h5ad"
        # Get AnnData object:
        if not os.path.isfile(return_path):
            if is_racipe:
                grins_data = grins_racipe_to_adata(path_to_data,pert_list=pert_list) 
            else:
                grins_data = grins_ising_to_adata(path_to_data, grn_file) 
            
            # Create final subsets:
            if experimental and pert_list is not None:
                print("Subsetting experimental data")
                grins_data = get_subset_adata_all(grins_data,grn_file,max_missingness=max_missingness)

            print("Generate missing indices...")
            if pert_list is None:
                grins_data.layers["missing_matrix"] = missingness_filter(pd.DataFrame(grins_data.X.todense()).values,loc=100-max_missingness,scale=expon_scale,full_dropouts=full_dropouts)
            else:
                grins_data.layers["missing_matrix"] = scipy.sparse.vstack([missingness_filter(pd.DataFrame(grins_data[grins_data.obs["PertNum"]==i].X.todense()).values,loc=100-max_missingness,scale=expon_scale,full_dropouts=full_dropouts) for i in range(len(pert_list))])

            grins_data.X = sparse.csc_matrix.multiply(grins_data.X.tocsc(),grins_data.layers["missing_matrix"].tocsc()).tocsc()#apply_missingness(grins_data)

            if is_racipe:
                grins_data = normalize_grins_adata(grins_data)    
            else:
                grins_data = grins_ising_to_continuous(grins_data,exp_data)

            # Save the object:
            print(f"Save the AnnData object to {return_path}...")
            ad.settings.allow_write_nullable_strings = True
            grins_data.write_h5ad(
                f"{return_path}",
                compression=hdf5plugin.FILTERS["zstd"]
            )

        else:
            print("Reading h5ad file...")
            grins_data = sc.read_h5ad(return_path)    

    return grins_data


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("grn", help="Name of the GRN used in the project")
    parser.add_argument("-e", "--experimental", action="store_true",help="Whether or not experimental data is used for comparison.")
    parser.add_argument("-m","--method", help="Racipe or Ising (Defaults to Racipe.)")
    parser.add_argument("-p", "--use_perts", action="store_true",help="Whether or not pertubations should be analyzed. If true, Data/Perts/grn_perts.pert is loaded. Specify a different filename in Data/Perts/filename.pert with --pert_file in addition to -p.")
    parser.add_argument("--pert_file", help="A list of perturbations to process other than grn_perts.pert.")
    parser.add_argument("--max_missingness", type=float,help="The maximal percentage of missing data (Default: 90 percent).")
    parser.add_argument("--expon_scale",type=float,help="Given an experimental dataset, this is the mean of pct_dropout_by_counts from adata.var among the genes with pct_dropout_by_counts<max_missingness (Default: 42.2 for Replogle22)")
    parser.add_argument("--full_dropouts",type=float,help="How many genes should have 100 percent of their entries missing (Default: 0 percent)")
    parser.add_argument("--num_replicates", type=int,help="Number of replicates to be simulated (Default: 1)")
    parser.add_argument("--mode", help="If Ising, sync or async (Default: async)")

    args = parser.parse_args()

    grn_file = args.grn
    if args.method and args.method.lower() == "ising":
        is_racipe = False
    else:
        is_racipe = True

    if args.experimental:
        experimental = True
    else:
        experimental = False

    if args.use_perts:
        if args.pert_file:
            pert_file = args.pert_file
        else:
            pert_file = f"{grn_file}_perts"
    else:
        pert_file = None

    kwargs = {}
    if args.max_missingness:
        kwargs["max_missingness"] = args.max_missingness
    if args.expon_scale:
        kwargs["expon_scale"] = args.expon_scale
    if args.full_dropouts:
        kwargs["full_dropouts"] = args.full_dropouts
    if args.num_replicates:
        kwargs["num_replicates"] = args.num_replicates
    if args.mode:
        kwargs["mode"] = args.mode
    
        
    main(grn_file, experimental, is_racipe, pert_file, **kwargs)