import numpy as np
import pandas as pd

from scipy import sparse
from scipy.stats import expon

import scanpy as sc
import anndata as ad

import os
from tqdm import tqdm
from glob import glob
import pickle

from Prep_Data import pgrins_prepare_input, normalize



def grins_racipe_to_adata(grn_file : str, path_to_data : str, split_sinks : bool = False, replicate : int = 1, pert_list : list = [], outlier_cutoff_min_pct : float = 0.01, outlier_cutoff_max : float = 10000, remove_outliers : bool = False) -> ad.AnnData:
    """
    Takes a .parquet file containing the steady states generated by RACIPE and turns it into an AnnData object.
    Do note that the steady state entries in grins_data.X are not discrete. 
    After the unperturbed simulation, the full .parquet file is used, to generate an unperturbed adata object.
        After the perturbed simulation, first steadystate_solutions_ctrl.parquet (and ctrl_sinks.parquet) are subset by the cells of the best cluster as stored in ctrl_best_cells.pickle (generated in pgrins_cluster.py),
        then they are vstacked with the perturbed cells from steadystate_solutions_pert.parquet (and pert_sinks.parquet).
    Some initial quality control detects any entries in the raw data that are negative or NA (due to numerical instability in the simulation) or that are very high. If wanted, these can be removed.

    Parameters:
    -----------
    path_to_data : str
        A path to the file name of the data generated by GRiNS, without the name extension (.parquet, .csv, .h5ad, ...).
    pert_list : list, optional
        A list of dictionaries for each perturbation set, if applicable.
    max_missingness : float, optional
        The maximal percentage of cells for each gene that should be able to be missing.
    expon_scale : float, optional
        The scale of the exponential distribution used for missingness sampling.
    full_dropouts : float, optional
        How many genes should have 100% missingness.
    outlier_cutoff_min_pct : float, optional
        What percentage of cells of a gene should be negative or missing in order for them to be removed. Defaults to 1%.
    outlier_cutoff_max : float, optional
        How high the mean raw counts should be in order to be treated as an outlier. Defaults to 10000. For reference, Norman19 and Replogle22 have few genes with >100 raw counts.
    remove_outliers : bool, optional
        If True, outlier genes are removed. Otherwise, they are set to zero.

    Returns:
    --------
    grins_data : ad.AnnData
        An AnnData object containing the GRiNS steady state solutions.
    """

    # Get control cell .parquet files:
    if split_sinks:
        sol_df = pd.concat([pd.read_parquet(f"{path_to_data}_ctrl.parquet"),pd.read_parquet(f"{path_to_data}_sinks_ctrl.parquet")],axis=1)
    else:
        sol_df = pd.read_parquet(f"{path_to_data}_ctrl.parquet")
    if pert_list != []:
        print("Loading perturbed data...")
        # For perturbed (full) results, subset by best cells:
        with open(f'Data/Projects/{grn_file}/{replicate:03}/ctrl_best_cells.pickle', 'rb') as f:
            best_cells = pickle.load(f)
            best_cell_tups = [(int(cell.split("_")[1]),int(cell.split("_")[2])) for cell in best_cells]
        # Keep cells where (InitCondNum,ParamNum) is in best_cells:
        tuples_in_df = pd.MultiIndex.from_frame(sol_df[["InitCondNum","ParamNum"]])
        sol_df = sol_df[tuples_in_df.isin(best_cell_tups)]

        # Get pert .parquet files:
        if split_sinks:
            pert_sol_df = pd.concat([pd.read_parquet(f"{path_to_data}_pert.parquet"),pd.read_parquet(f"{path_to_data}_sinks_pert.parquet")],axis=1)[sol_df.columns] # Remove source genes not in adata from pert_df
        else:
            pert_sol_df = pd.read_parquet(f"{path_to_data}_pert.parquet")[sol_df.columns]
        # Concat them:
        sol_df = pd.concat([sol_df,pert_sol_df],axis=0,ignore_index=True)
        del pert_sol_df

    # Store important information in separate df (later turned into .obs) so that sol_df only contains steady states
    info_df = sol_df.loc[:,["PertNum","InitCondNum","ParamNum","SteadyStateFlag","Time"]].astype(int) # Contains combination of ICs and params and perts
    sol_df = sol_df.loc[:,[col for col in list(sol_df.columns) if ("gk_" not in col) & (col not in list(info_df.columns))]]
    # GRiNS internally replaces "-" with "_" so that it can name its parameters after the genes
    sol_df.columns = [col.replace("_","-") for col in sol_df.columns] 
    sol_df = sol_df.reindex(sorted(sol_df.columns),axis=1)

    # QC:
    zero_genes = pd.Series([np.sum(sol_df[col]==0) for col in list(sol_df.columns)]) # Biological zeroes, not removed just noted
    minus_genes = np.asarray(list(sol_df.columns))[np.asarray([np.sum(sol_df[col]<0) for col in list(sol_df.columns)])>sol_df.shape[0]*outlier_cutoff_min_pct] # Negative entries, must be treated
    na_genes = np.asarray(list(sol_df.columns))[np.asarray([np.sum(sol_df[col].isna()) for col in list(sol_df.columns)])>sol_df.shape[0]*outlier_cutoff_min_pct] # NA entries, must be treated
    outlier_genes = np.asarray(list(sol_df.columns))[np.mean(sol_df,axis=0)>outlier_cutoff_max] # Positive outliers, can be treated
    
    print(f"There are {np.sum(zero_genes)} zero entries ({np.round(100*np.sum(zero_genes)/(sol_df.shape[0]*sol_df.shape[1]),3)}% of all entries).")
    print(f"Out of {sol_df.shape[1]} genes, there are {len(minus_genes)} genes with more than {100*outlier_cutoff_min_pct}% of entries being negative, and {len(na_genes)} genes with more than {100*outlier_cutoff_min_pct}% of entries being NaN.")
    print(f"There are also {len(outlier_genes)} genes that have a mean expression of >{outlier_cutoff_max}.")
     
    if remove_outliers:
        pgenes = set().union(*[set(list(p.keys())) for p in pert_list])
        remove_genes = (set(minus_genes) | set(na_genes) | set(outlier_genes)) - pgenes # Keep perturbed genes, as well as all genes that are not outliers
        print(len(remove_genes),"genes are dropped.")
        sol_df.drop(list(remove_genes),axis=1,inplace=True)

    # Negative & NA entries of genes not dropped need to be treated as well
    sol_df = sol_df.fillna(0)
    sol_df[sol_df[:]<0]=0 

    # Create the AnnData object:
    print("Create AnnData object...")
    grins_data = ad.AnnData(sparse.csc_matrix(sol_df.values))
    grins_data.obs = info_df
    
    # Add perturbation column
    grins_data.obs["perturbation"] = np.array(["_".join(sorted(list(pert_list[int(i)].keys()))) if i != -1 else "ctrl" for i in grins_data.obs["PertNum"].values])

    grins_data.obs_names = [f"{int(info_df.loc[i,"PertNum"])}_{int(info_df.loc[i,"InitCondNum"])}_{int(info_df.loc[i,"ParamNum"])}_{i}" for i in range(info_df.shape[0])]
    grins_data.var_names = list(sol_df.columns)
    
    # Process for GEARS:
    if pert_list != []:
        grins_data.obs["cell_line"] = "syn"
        normalize.process_GEARS(grins_data)

    return grins_data



def missingness_filter(grins_matrix : sparse.csc_matrix, loc : float = 10, scale : float = 42.2, full_dropouts : float = 0,zero_dropouts : float = 5) -> sparse.csc_matrix:
    """
    Inserts missing entries into the raw grins matrix (m cells, n genes) according to the following procedure:
        1. n missing counts l_hat are sampled from an exponential distribution fit to the Replogle dataset (meaning without full dropouts, aka. pct_dropouts<=90)
            - Then, the mean of the counts is calculated as mu, and loc=0 and lambda=scale=1/mu are used (alternatively, it is also possible to fit scipy.stats.expon to the histogram).
            - Since the distribution is fit from [0,inf), but the data is in [10,100], loc is set to 10 and all values >100 are set to 100; this is also sensible since there is a significant amount of genes with exactly 0 dropouts, which an exponential distribution alone would not capture.
            - However, in case this leads to too few/too many genes with zero dropouts, this is corrected by setting random non-100 entries in rvs to 100 or by resampling some 100 entries from the exponential distribution.
        2. Assuming that a gene with a lower average expression should have more missing entries, both the average expressions across genes and l_hat are ranked.
        3. Each gene j is assigned the l_hat,j of the same rank, meaning that it should have that many missing entries.
        4. Each entry ij should have a higher missingness probability the lower its expression is; therefore, assign the probability 1/(x_ij+1), and normalize these so that all probabilities add up to 1.
        5. Perform Weighted Random Sampling (WRS) without replacement using an algorithm described by Efraimidis and Spirakis (2005) to set l_hat,j many entries to 0.
    This way, only the entries with the highest expression for low-expression genes will be kept, while high-expression genes will only have few genes removed.

    Parameters:
    -----------
    grins_matrix : np.matrix
        The raw counts.
    loc : float, optional
        How far to the right the distribution should be shifted. Equivalent to the minimal number of non-zeroes per gene (100-max_missingness).    
    scale : float, optional
        The scale of the exponential distribution used for missingness sampling.
    full_dropouts : float, optional
        What percentage of genes should have 100 percent of their entries missing.
    zero_dropouts : float, optional
        What percentage of genes should have 0 percent of their entries missing.

    Returns:
    --------
    missing_matrix : sparse.csc_matrix
        A sparse matrix where all dropout entries are 0 and all entries to be kept are 1.
    """
    expon_params = (loc,scale) # (10,42.2) for Replogle
    missing_matrix = np.ones(grins_matrix.shape)

    # Genes sorted from high to low expression (due to the low number of zero entries, I did not calculate the nonzero mean here, as it would be more or less the same)
    gene_mean_order = np.asarray(np.argsort(np.mean(grins_matrix,axis=0))).squeeze()[::-1]

    # All values above 100% non-missingness make no sense
    rvs = np.sort(np.array([x if x < 100 else np.float64(100) for x in expon.rvs(*expon_params,size=grins_matrix.shape[1])]))
    # How many genes will have 0% dropouts according to rvs:
    zero_dropouts_rvs = len(rvs[np.abs(rvs-100.0)<1e-5])-int(grins_matrix.shape[1]*zero_dropouts/100)
    # If too few zero dropouts, artifically add some:
    
    if zero_dropouts_rvs < 0:
        for i in np.random.choice(range(len(rvs)+zero_dropouts_rvs),-zero_dropouts_rvs,replace=False):
            rvs[i]=np.float64(100)
    # If too many zero dropouts, remove them and concatenate new rvs
    elif zero_dropouts_rvs > 0:
        rvs = rvs[:len(rvs)-zero_dropouts_rvs]
        rvs = np.concatenate([rvs,np.array([x if x < 100 else np.float64(100) for x in expon.rvs(*expon_params,size=zero_dropouts_rvs)])])
    # The number of missing cells per gene with same rank, 1-x/100 is necessary because rvs contains the percentage of cells NOT missing; sorted from low to high number of dropouts
    missing_rates = np.sort((grins_matrix.shape[0]*(1-rvs/100)).astype(int))
    
    for j in range(len(gene_mean_order)): # Start with gene with highest expression level, assign to it the lowest dropout rate

        # Calculate the number of already zero entries (biological zeroes); if there are more than missing_rates[j], no technical zeroes need to be added
        # Also, these positions don't need to be set to zero later since they already are zero
        nonzero_rows = np.where(np.asarray(grins_matrix[:,gene_mean_order[j]]).squeeze()!=0)[0]
        if grins_matrix.shape[0]-len(nonzero_rows)>=missing_rates[j]:
            continue
        
        # For each entry ij of gene j, calculate the probability that it should be missing; their sum should add up to 1
        gene_missing_prob = (1/((grins_matrix[nonzero_rows,gene_mean_order[j]]+1)*np.sum(1/(grins_matrix[nonzero_rows,gene_mean_order[j]]+1)))) 
        # Weighted random sampling across the entries that are not (yet) zero:
        keys = np.exp(np.random.rand(len(nonzero_rows)),1/gene_missing_prob)

        # Assign missingness probabilities to remaining nonzero positions:
        prob_pos = np.zeros(grins_matrix.shape[0])
        prob_pos[nonzero_rows] = keys

        # From these, sample the top missing_rates[j] cells with the highest missingness probability (minus the number of cells already zero)
        wrs_positions = np.argsort(prob_pos)[::-1][:missing_rates[j]-(grins_matrix.shape[0]-len(nonzero_rows))]

        # Set the selected cells for the gene to zero
        if len(wrs_positions)>0:
            missing_matrix[wrs_positions,gene_mean_order[j]]=0

    # Add full dropouts, if desired
    num_dropouts = int(missing_matrix.shape[1]*full_dropouts/100)
    if num_dropouts > 0:
        missing_matrix[:,np.random.choice(list(range(missing_matrix.shape[1])),num_dropouts,replace=False)] = 0
    
    return sparse.csc_matrix(missing_matrix)



def normalize_grins_adata(grins_data : ad.AnnData) -> ad.AnnData:
    """
    Takes the AnnData object just created (with missingness) and normalizes it, following the normalization pipeline from the software project.
    This is necessary because the raw data is overdispersed.

    Parameters:
    -----------
    grins_data : ad.AnnData
        The unnormalized AnnData object containing the simulation results.
    """
    # Calculate QC metrics:
    print("Calculate QC metrics...")
    sc.pp.calculate_qc_metrics(grins_data,percent_top=[20],inplace=True,log1p=True,layer="missing_matrix")
    
    # Log-normalize the layers, excluding positive outliers:
    print("Normalize Data...")  
    grins_data.layers["log1p"] = grins_data.layers["missing_matrix"].copy().tocsc()
    sc.pp.normalize_total(grins_data, target_sum=1e6,layer="log1p",exclude_highly_expressed=True)
    sc.pp.log1p(grins_data, layer="log1p")

    return grins_data



def grins_ising_to_adata(path_to_data : str, grn_file : str) -> ad.AnnData:
    """
    Takes the state counts saved in a .csv file and turns them into an Anndata object.
    Do note that the on/off states in grins_data.X should not be regarded as counts.

    Parameters:
    -----------
    path_to_data : str
        A path to the file name of the data generated by GRiNS, without the name extension.
    grn_file : str
        The name of the project.

    Returns:
    --------
    grins_data : ad.AnnData
        An AnnData object containing the discrete states of GRiNS.
    """
 
    print(f"Read {path_to_data}.csv...")
    sol_df = pd.read_csv(f"{path_to_data}.csv")
    sol_matrix = np.asarray([list(string) for string in sol_df["State"].values],dtype=int) # if '100101011...', then list(string[1:-1])
    grn = pd.read_csv(f"Data/{grn_file}/{grn_file}.topo",sep=" ")
    grn_genes = sorted(list(set(grn["Source"])|set(grn["Target"])))

    sol_sparse = sparse.csc_matrix(sol_matrix)
    grins_data = ad.AnnData(sol_sparse)
    grins_data.obs_names = sol_df["Initnum"]
    grins_data.var_names = grn_genes
    grins_data.obs["Replicate"] = sol_df["Replicate"].values
    grins_data.obs["Mode"] = sol_df["Mode"].values

    return grins_data



def main(grn_file : str, experimental : bool, is_racipe : bool = False, split_sinks : bool = False, pert_file : str = None, num_replicates : int = 1, mode : str = "async", max_missingness : float = 90, expon_scale : float = 42.2, full_dropouts : float = 0, zero_dropouts : float = 5, outlier_cutoff_min_pct : float = 0.01, outlier_cutoff_max : float = 10000, remove_outliers : bool = False) -> ad.AnnData:
    """
    Turns either the steady states generated by Racipe or the discrete on/off states generated by Ising into an Anndata object (only the control cells for the unperturbed run, control cells and perturbed cells for the perturbed run).
    Then, a missingness filter is applied perturbation-wise so that the cellwise and genewise missingness rates of the synthetic data mimic those observed in experimental data.
    The results are then log-normalized and (if experimental data is provided) scaled so that the mean of the log1p layer of the control cells of the synthetic and experimental data are the same.

    Parameters:
    -----------
    grn_file : str
        The name of the project.
    experimental : bool
        Whether or not experimental data is provided.
    is_racipe : bool
        A boolean indicating whether or not the data is generated through Racipe or Ising. Defaults to True (Racipe).
    split_sinks : bool, optional
        Whether or not the sink nodes should be treated separately and not simulated in Racipe.
    pert_file : str, optional
        Name of the .pert file, if applicable.
    num_replicates : int, optional
        The number of replicates for the simulation. Defaults to 1.
    mode : bool, optional
        Indicating whether or not the Ising results are generated using sync or async updates.
    max_missingness : float, optional
        The maximal percentage of cells per gene that can have missing entries (for both synthetic and experimental data). Defaults to 90 (no genes with <10% nonzero values).
    expon_scale : float, optional
        The scale of the exponential distribution used for genewise missingness sampling. Given an experimental dataset, this value can be calculated as the mean of pct_dropout_by_counts from exp_adata.var among the genes with pct_dropout_by_counts<max_missingness. Defaults to 42.2 (taken from Replogle22).
    full_dropouts : float, optional
        What percentage of genes should have 100 percent of their entries missing. Defaults to 0. If max_missingness != 100, setting this >0 could lead to a gap in the genewise missingness distribution.
    zero_dropouts : float, optional
        What percentage of genes should have 0 percent of their entries missing. Defaults to 5 (taken from Replogle22).
    outlier_cutoff_min_pct : float, optional
        What percentage of cells of a gene should be negative or missing in order for them to be removed. Defaults to 0.01.
    outlier_cutoff_max : float , optional 
        How high the mean raw counts should be in order to be treated as an outlier. Defaults to 10000.
    remove_outliers : bool, optional
        If True, outlier genes are removed. Otherwise, negative and NA values are set to zero, and very large entries are kept unchanged. Defaults to False.

    Returns:
    --------
    None
    Results are saved in Projects/{grn_file}/perturb_norm_ctrl.h5ad after the unperturbed run, and Projects/{grn_file}/perturb_norm_full.h5ad after the perturbed run.
    """

    assert max_missingness >= 0 and max_missingness <= 100
    assert expon_scale >= 0
    assert full_dropouts >= 0 and full_dropouts <= 100

    if pert_file is not None:
        pert_list = pgrins_prepare_input.extract_pert_info(grn_file,pert_file)
        suffix = "full"
    else:
        pert_list = []
        suffix = "ctrl"        

    for replicate in range(1,num_replicates+1):
        os.makedirs(f"Data/Projects/{grn_file}/{replicate:03}",exist_ok=True)
        # Get file path to data:
        if is_racipe:
            path_to_data = f"Data/SimulResults_Racipe/{grn_file}/{replicate:03}/{grn_file}_steadystate_solutions_{replicate:03}"
        else:
            path_to_data = f"Data/SimulResults_Ising/{grn_file}/{replicate}/{grn_file}_{mode}_SteadyStates"

        return_path = f"Data/Projects/{grn_file}/{replicate:03}/perturb_norm_{suffix}.h5ad"
        
        if not os.path.isfile(return_path):
            # Generate AnnData object:
            print(f"Read {path_to_data}...")
            if is_racipe:
                grins_data = grins_racipe_to_adata(grn_file,path_to_data,split_sinks=split_sinks,replicate=replicate,pert_list=pert_list,outlier_cutoff_min_pct=outlier_cutoff_min_pct, outlier_cutoff_max=outlier_cutoff_max, remove_outliers=remove_outliers) 
            else:
                grins_data = grins_ising_to_adata(path_to_data, grn_file) 
            
            print("Generate missing indices...")
            if pert_list == []:
                grins_data.layers["missing_matrix"] = missingness_filter(pd.DataFrame(grins_data.X.todense()).values,loc=100-max_missingness,scale=expon_scale,full_dropouts=full_dropouts)
            else:
                grins_data.layers["missing_matrix"] = sparse.vstack([missingness_filter(pd.DataFrame(grins_data[grins_data.obs["PertNum"]==i].X.todense()).values,loc=100-max_missingness,scale=expon_scale,full_dropouts=full_dropouts) for i in tqdm(range(-1,len(pert_list)))])

            grins_data.layers["missing_matrix"] = sparse.csc_matrix.multiply(grins_data.X.tocsc(),grins_data.layers["missing_matrix"].tocsc()).tocsc()
            
            # Normalize:
            if is_racipe:
                grins_data = normalize_grins_adata(grins_data)    
            
            adata_genes = set()
            if experimental:
                # Comparing experimental and synthetic data is meaningless if the expression vectors have a similar direction, but different magnitude
                scale_factor = 0
                pseq_paths = glob(f"Data/Experimental/*")
                for pseq_path in pseq_paths:
                    # Get the mean value in the log1p layer for the control cells of each experimental dataset...
                    adata = sc.read_h5ad(f"{pseq_path}/perturb_norm_subset_{grn_file}.h5ad")
                    adata = adata[:,adata.var_names.isin(grins_data.var_names)]
                    adata_genes = adata_genes.union(set(adata.var_names))
                    scale_factor += np.mean(adata[adata.obs["perturbation"]=="ctrl"].layers["log1p"])
                # ...then scale the synthetic data by the mean of these means
                grins_data.layers["log1p"] *= scale_factor/(len(pseq_paths)*np.mean(grins_data[grins_data.obs["perturbation"]=="ctrl"].layers["log1p"]))
                # Remove all genes not in adata (i.e. some of the source genes)
                grins_data = grins_data[:,sorted(list(adata_genes))]
            # Save the object:
            print(f"Save the AnnData object to {return_path}...")
            grins_data.write_h5ad(return_path) 

        else:
            print("Done!")