import anndata as ad
import scanpy as sc
import hdf5plugin
from scipy import sparse
import pandas as pd
import numpy as np
import os


def get_grn(output_name : str, topo_files : list[str] = None):
    """
    After the .topo files for individual GRNs have been created, read and combine them.

    Parameters:
    -----------
    topo_files : list[str]
        A list of names of .topo files to be combined. They must have the column names "Source", "Target", and "Type", where Type=1 for an activating and Type=2 for an inhibiting regulation.
    output_name : str
        The name of the resulting .topo file used for further analysis.
    
    grn_df : DataFrame
        The created dataframe.
    """
    out_path = f"Data/{output_name}/{output_name}.topo"

    if not os.path.isfile(outpath):
        topo_dfs = [pd.read_csv(f"Data/Topos/{grn_file}.topo",sep=" ") for grn_file in topo_files]
        grn_df = pd.unique(pd.concat(topo_dfs,axis=1)).sort_values(by=["Source","Target"])

        os.makedirs(f"Data/{output_name}",exist_ok=True)
        grn_df.to_csv(outpath,sep=" ",index=False)
    else:
        grn_df = pd.read_csv(outpath,sep=" ")

    return grn_df


def subset_datasets(grn_file, topo_files : list[str], adata_dict : dict,subset : str = "Union"): # Filenames + update csv path
    """
    Takes a GRN and normalized anndata objects as inputs.
    After updating the gene names, all genes in the anndata objects not in the GRN are removed.
    From the GRN, genes not present in any | all of the adata sets are removed.
    
    Parameters:
    -----------
    grn_df : str
        The name of the combined GRN.
    topo_files : list[str]
        A list of names of .topo files to be combined. They must have the column names "Source", "Target", and "Type", where Type=1 for an activating and Type=2 for an inhibiting regulation.
    adata_dict : dict[str,anndata.AnnData]
        A dictionary of all the dataset names as keys and the normalized adata files as values.
    subset : str
        How the genes are subset. Choices are ["union", "intersection"].
    """
    grn_df = get_grn(grn_file,topo_files)

    grn_genes = set(list(grn_df["Source"])+list(grn_df["Target"]))

    adata_genes_list = []
    for filename, adata in adata_dict.items():
        adata_genes = set(adata.var_names)
        adata = adata[:,sorted(list(grn_genes & adata_genes))]
        adata_genes_list.append(adata_genes)

        sc.pp.highly_variable_genes(adata,n_top_genes=5000, subset=False,layer="log1p")

        os.remove(f"Data/{filename}/perturb_norm.h5ad")
        ad.settings.allow_write_nullable_strings = True
        adata.write_h5ad(
            f"Data/{filename}/perturb_norm.h5ad",
            compression=hdf5plugin.FILTERS["zstd"]
        )

    if subset == "Union":
        all_adata_genes = list(set().union(*adata_genes_list))
    elif subset == "Intersection":
        all_adata_genes = list(set().intersection(*adata_genes_list))
    else:
        raise Exception("subset is incorrect.")

    grn_remaining_genes = sorted(list(grn_genes & all_adata_genes))

    grn_df_subset = grn_df.loc(grn_df["Source"] in grn_remaining_genes)
    grn_df_subset = grn_df.loc(grn_df["Target"] in grn_remaining_genes)

    os.remove(f"Data/{grn_file}/{grn_file}.topo")
    grn_df_subset.to_csv(f"Data/{grn_file}/{grn_file}.topo",sep=" ",index=False)

    return grn_df_subset, adata_dict


def extract_pert_info(pert_file):
    """
    Takes a perturbation list file and turns it into a list of perturbations, including their types
    """
    pass


def perts_from_adata():
    """
    Turns certain perturbations from an adata object into a list that is inputtable into extract_pert_info.
    """
    pass



def steadystate_to_grins(path_to_data : str, zero_cutoff : int):
    """
    Takes a .parquet file containing the steady states generated by GRiNS-Racipe and turns it into an AnnData object.
    Do note that the steady state entries in grins_data.X are not discrete. 

    Parameters:
    -----------
    path_to_data : str
        A path to the file name of the data generated by GRiNS, without the name extension (.parquet, .csv, .h5ad, ...).
    zero_cutoff : float
        A threshold where steady state concentrations below this value will be set to 0.

    Returns:
    --------
    grins_data : anndata
        An AnnData object containing the GRiNS steady state solutions.
    """

    print(f"Read {path_to_data}.parquet...")
    sol_df = pd.read_parquet(f"{path_to_data}.parquet")
    
    # Create the AnnData object:
    print("Create AnnData object...")
    gk_cols = [col for col in sol_df.columns if "gk_" in col]
    gene_cols = [col.replace("gk_", "") for col in sol_df.columns if "gk_" in col]
    sol_matrix = sol_df.loc[:,gene_cols].values
    if zero_cutoff > 0.0:
        for i in range(sol_matrix.shape[0]):
            if i % 100000 == 0:
                print(i)
            for j in range(sol_matrix.shape[1]):
                if sol_matrix[i,j] < zero_cutoff:
                    sol_matrix[i,j] = 0
    
    sol_sparse = sparse.csc_matrix(sol_matrix)
    grins_data = ad.AnnData(sol_sparse)
    grins_data.obs_names = [str(sol_df.loc[:,"param_index"][i])+"_"+str(sol_df.loc[:,"ic_index"][i]) for i in range(sol_df.shape[0])]
    grins_data.var_names = gene_cols
    return grins_data


def discrete_to_grins(path_to_data : str, is_racipe : bool):
    """
    Takes the state counts saved in a .csv file and turns them into an Anndata object.
    Do note that the on/off states in grins_data.X should not be regarded as counts whatsoever.

    Parameters:
    -----------
    path_to_data : str
        A path to the file name of the data generated by GRiNS, without the name extension (.parquet, .csv, .h5ad, ...).
    is_racipe : bool
        A boolean to indicate whether or not the data is generated through Racipe (True) or Ising (False).

    Returns:
    --------
    grins_data : anndata
        An AnnData object containing the discrete states of GRiNS.
    """
    pass


def normalize_grins(grins_data):
    """
    Takes the AnnData object just created and normalized it, following the normalization pipeline from the software project.
    """

    # Log-normalize the layers:
    print("Normalize Data...")
    grins_data.layers["normalized"] = grins_data.X.copy()
    sc.pp.normalize_total(grins_data, target_sum=None,layer="normalized")
    grins_data.layers["log1p"] = grins_data.layers["normalized"].copy()
    sc.pp.log1p(grins_data, layer="log1p")
    
    # Calculate QC metrics:
    print("Calculate QC metrics...")
    sc.pp.calculate_qc_metrics(grins_data,percent_top=[20],inplace=True)

    return grins_data


def grins_to_adata(path_to_data : str, is_racipe : bool, is_discrete : bool = True, zero_cutoff : float = 0.0):
    """
    Turns either the steady states generated by Racipe or the discrete on/off states generated by Racipe or Ising and turns them into an Anndata object.

    Parameters:
    -----------
    path_to_data : str
        A path to the file name of the data generated by GRiNS, without the name extension (.parquet, .csv, .h5ad, ...).
    is_racipe : bool
        A boolean indicating whether or not the data is generated through Racipe (True) or Ising (False).
    is_discrete : bool
        A boolean indicating whether the steady states.
    zero_cutoff : float
        A threshold where steady state concentrations below this value will be set to 0.

    Returns:
    --------
    grins_data : anndata
        An AnnData object containing the discrete states of GRiNS.

    Examples:
    ---------
    racipe_data = grins_to_adata(path_to_data, is_racipe = True, is_discrete = False, zero_cutoff = 0.1)
    ising_data = grins_to_adata(path_to_data, is_racipe = False)
    """
    # Get file path to data:
    if is_racipe:
        if is_discrete: # Discrete RACIPE state counts
            path_to_data = f"Data/SimulResults_Racipe/{topo}/00{replicate}/{topo}_steadystate_counts_00{replicate}"
        else: # Continuous RACIPE concentrations
            path_to_data = f"Data/SimulResults_Racipe/{topo}/00{replicate}/{topo}_steadystate_solutions_00{replicate}-{str(zero_cutoff).replace(".","_")}"
    else:
        if is_sync: # Sync Ising state counts
            path_to_data = f"Data/SimulResults_Ising/{topo}/{replicate}/{topo}_sync_ising_results"
        else: # Async Ising state counts
            path_to_data = f"Data/SimulResults_Ising/{topo}/{replicate}/{topo}_async_ising_results"


    # Get AnnData object:
    if not os.path.isfile(f"{path_to_data}.h5ad"):
        if is_discrete:
            grins_data = discrete_to_grins(path_to_data, is_racipe) 
        else:
            if not is_racipe:
                raise Exception("Ising does not generate any steady states. Therefore, is_discrete = False and is_racipe = False are not compatible.")
            grins_data = steadystate_to_grins(path_to_data.split("-")[0], zero_cutoff) # Remove the zero_cutoff index from the data path
        # Normalize:
        grins_data = normalize_grins(grins_data)    

        # Save the object:
        print(f"Save the AnnData object to {path_to_data}.h5ad...")
        ad.settings.allow_write_nullable_strings = True # <- remove later
        grins_data.write_h5ad(
            f"{path_to_data}.h5ad", # maybe change path later
            compression=hdf5plugin.FILTERS["zstd"]
        )
    else:
        print("Reading h5ad file...")
        grins_data = sc.read_h5ad(f"{path_to_data}.h5ad")    

    return grins_data


def save_full_grins():
    # Takes the adata object from control and perturb cells as input, concatenates them, and saves them as full h5ad file
    pass


def missingness_filter():
    # If control data is available: maybe use something like scImpute (https://pmc.ncbi.nlm.nih.gov/articles/PMC12908672/) to find probability of a zero being a dropout
    # Then calculate for each gene the percentage of dropouts and use that to create dropouts in synth data

    # Otherwise, maybe do the same but average over literature data? if that exists?

    # New general idea:
    """
    if control_data supplied:
        fit gamma-norm prob on the expression histogram across all control cells j for each gene i
        lambda_biol,i is the biological dropout rate; compare it to dropout rate lambda_grins,i in grins (which should all be biological)
        maybe scale lambda_tech,i somehow so that lambda_biol,i=lambda_grins,i?
        lambda_total,i=lambda_tech,i+lambda_biol,i=1-nnv/n
        however, scaling it like this (multiplying by lamba_biol/lambda_grins=k) could mean that k(1-nnv/n)>1, which doesnt make sense
        finally: 
    """

    # Other approach:
    """
    say that lambda_biol,i=lambda_grins,i and simply set lambda_tech,i=1-nnv/n-lambda_grins,i
    then, plot the mean of the non-dropout expression levels for each gene against its lambda_tech,i technical dropout rate and fit a curve
    use this curve to impute how many non-zero entries in grins should be set to 0 (tech dups)

    but what if (theoretically) lambda_grins,i > 1-nnv/n -> lambda_tech,i<0
        especially the case if some gene is always zero in grins because of GRN design
        maybe skip those (already enough missingness)
    """

    # Approach without control data, purely from grins:
    """
    Idea: 
    """
    pass

def get_dist_matrix():
    pass

def calc_clusters():
    # Silhouette Score
    pass

def reduce_param_ranges():
    # Get param ranges of best cluster as .csv
    pass

def set_param_ranges():
    pass